import React from 'react';
import { ChevronDown } from 'lucide-react';
import { useAppStore } from '../services/store';
import { rtkKanjiList } from '../data/rtkKanji';
import { FEED_TOPICS, DEFAULT_FEED_TOPICS } from '../data/feedTopics';

const stepperBtnStyle = (disabled: boolean): React.CSSProperties => ({
  width: '34px',
  height: '34px',
  borderRadius: '100px',
  border: 'none',
  backgroundColor: 'var(--border-light)',
  color: disabled ? 'var(--text-muted)' : 'var(--text-main)',
  fontSize: '1.2rem',
  fontWeight: 700,
  lineHeight: 1,
  cursor: disabled ? 'default' : 'pointer',
  opacity: disabled ? 0.4 : 1,
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
});

const lengthRows = [
  { kind: 'full', label: 'Full text', hint: 'Whole article body (badged FULL TEXT)' },
  { kind: 'partial', label: 'Partial', hint: 'A richer-than-teaser excerpt' },
  { kind: 'snippet', label: 'Snippet', hint: 'Only a short headline teaser' },
] as const;

export function Settings() {
  const {
    jlptLevel, setJlptLevel,
    rtkLevel, setRtkLevel,
    studyMode, setStudyMode,
    readingIntensity, setReadingIntensity,
    targetParagraphs, setTargetParagraphs,
    feedTopics, setFeedTopics,
    newWordsPerDay, setNewWordsPerDay,
    readerFontSize, setReaderFontSize,
    readerFontWeight, setReaderFontWeight,
    lastStudyPacingResetTs,
    lastFuriganaRealignTs
  } = useAppStore();

  const intensityOptions = ['leisure', 'balanced', 'intensive'] as const;
  const intensityLabels = ['Leisure', 'Balanced', 'Intensive'] as const;
  const activeIntensityIndex = intensityOptions.indexOf(readingIntensity);

  const handleRtkChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const val = parseInt(e.target.value, 10);
    if (!isNaN(val)) {
      setRtkLevel(Math.min(Math.max(1, val), rtkKanjiList.length));
    }
  };

  // null = never chosen → the server-default lineup is what's effectively active.
  const selectedTopics = feedTopics ?? DEFAULT_FEED_TOPICS;
  const toggleTopic = (id: string) => {
    const next = selectedTopics.includes(id)
      ? selectedTopics.filter(t => t !== id)
      : [...selectedTopics, id];
    if (next.length === 0) return; // keep at least one topic on
    setFeedTopics(next);
  };

  const modes = ['Natural', 'Balanced', 'Study'] as const;
  const activeModeIndex = modes.findIndex(m => m.toLowerCase() === studyMode);

  const jlptLevels = [5, 4, 3, 2, 1];
  const activeJlptIndex = jlptLevels.indexOf(jlptLevel || 4);

  return (
    <div className="fade-in" style={{ paddingBottom: '6rem' }}>
      <h2 className="serif" style={{ fontSize: '2rem', marginBottom: '2.5rem', color: 'var(--text-main)' }}>Settings</h2>

      {/* 1. Grammar Level (JLPT) */}
      <div style={{ backgroundColor: 'var(--bg-card)', padding: '1.5rem', borderRadius: '16px', marginBottom: '1.5rem' }}>
        <label style={{ display: 'block', fontSize: '0.85rem', fontWeight: 600, color: 'var(--text-muted)', letterSpacing: '0.1em', marginBottom: '1.5rem', textTransform: 'uppercase' }}>
          Grammar Level (JLPT)
        </label>
        <div style={{ display: 'flex', backgroundColor: 'var(--border-light)', borderRadius: '100px', padding: '4px', height: '45px', position: 'relative' }}>
          
          <div style={{
            position: 'absolute',
            top: '4px',
            bottom: '4px',
            left: `calc(4px + ${activeJlptIndex} * (100% - 8px) / 5)`,
            width: `calc((100% - 8px) / 5)`,
            backgroundColor: 'var(--bg-pure)',
            borderRadius: '100px',
            boxShadow: '0 2px 8px rgba(0,0,0,0.1)',
            transition: 'all 0.4s cubic-bezier(0.4, 0, 0.2, 1)',
            zIndex: 0
          }} />

          {jlptLevels.map(n => (
            <button
              key={n}
              onClick={() => setJlptLevel(n)}
              style={{
                flex: 1,
                borderRadius: '100px',
                backgroundColor: 'transparent',
                color: jlptLevel === n ? 'var(--text-main)' : 'var(--text-muted)',
                fontWeight: jlptLevel === n ? 700 : 600,
                border: 'none',
                outline: 'none',
                cursor: 'pointer',
                transition: 'color 0.4s cubic-bezier(0.4, 0, 0.2, 1)',
                display: 'flex',
                justifyContent: 'center',
                alignItems: 'center',
                fontSize: '0.9rem',
                position: 'relative',
                zIndex: 1
              }}
            >
              N{n}
            </button>
          ))}
        </div>
        <p style={{ fontSize: '0.85rem', color: 'var(--text-muted)', marginTop: '1rem', lineHeight: 1.5 }}>
          Defines the complexity of the sentence structures and conjugations generated by the AI native speaker.
        </p>
      </div>

      {/* 2. Article Intensity */}
      <div style={{ backgroundColor: 'var(--bg-card)', padding: '1.5rem', borderRadius: '16px', marginBottom: '1.5rem' }}>
        <label style={{ display: 'block', fontSize: '0.85rem', fontWeight: 600, color: 'var(--text-muted)', letterSpacing: '0.1em', marginBottom: '1.5rem', textTransform: 'uppercase' }}>
          Article Intensity
        </label>

        <div style={{ display: 'flex', backgroundColor: 'var(--border-light)', borderRadius: '100px', padding: '4px', marginBottom: '1.2rem', height: '45px', position: 'relative' }}>
          <div style={{
            position: 'absolute',
            top: '4px',
            bottom: '4px',
            left: `calc(4px + ${activeIntensityIndex === -1 ? 1 : activeIntensityIndex} * (100% - 8px) / 3)`,
            width: `calc((100% - 8px) / 3)`,
            backgroundColor: 'var(--bg-pure)',
            borderRadius: '100px',
            boxShadow: '0 2px 8px rgba(0,0,0,0.1)',
            transition: 'all 0.4s cubic-bezier(0.4, 0, 0.2, 1)',
            zIndex: 0
          }} />

          {intensityOptions.map((opt, i) => {
            const isSelected = readingIntensity === opt;
            return (
              <button
                key={`i-${opt}`}
                onClick={() => setReadingIntensity(opt)}
                style={{
                  flex: 1,
                  borderRadius: '100px',
                  backgroundColor: 'transparent',
                  color: isSelected ? 'var(--text-main)' : 'var(--text-muted)',
                  fontWeight: isSelected ? 700 : 600,
                  border: 'none',
                  outline: 'none',
                  cursor: 'pointer',
                  transition: 'color 0.4s cubic-bezier(0.4, 0, 0.2, 1)',
                  fontSize: '0.85rem',
                  display: 'flex',
                  justifyContent: 'center',
                  alignItems: 'center',
                  position: 'relative',
                  zIndex: 1
                }}
              >
                {intensityLabels[i]}
              </button>
            );
          })}
        </div>

        <p style={{ fontSize: '0.85rem', color: 'var(--text-muted)', lineHeight: 1.5 }}>
          {readingIntensity === 'leisure' && 'Light reading — ~98% known vocabulary. Flow through articles with minimal dictionary lookups.'}
          {readingIntensity === 'balanced' && 'Comfortable learning — ~95% known, with a handful of review words and 1–2 new words per article.'}
          {readingIntensity === 'intensive' && 'Study-heavy — ~90% known, with more review and new vocabulary packed in. Slower but faster growth.'}
        </p>
      </div>

      {/* 2.5 Feed Topics (#10) */}
      <div style={{ backgroundColor: 'var(--bg-card)', padding: '1.5rem', borderRadius: '16px', marginBottom: '1.5rem' }}>
        <label style={{ display: 'block', fontSize: '0.85rem', fontWeight: 600, color: 'var(--text-muted)', letterSpacing: '0.1em', marginBottom: '1.5rem', textTransform: 'uppercase' }}>
          Feed Topics
        </label>
        <div style={{ display: 'flex', flexWrap: 'wrap', gap: '0.6rem', marginBottom: '1.2rem' }}>
          {FEED_TOPICS.map(topic => {
            const isOn = selectedTopics.includes(topic.id);
            return (
              <button
                key={topic.id}
                onClick={() => toggleTopic(topic.id)}
                title={topic.hint}
                style={{
                  padding: '0.5rem 1.1rem',
                  borderRadius: '100px',
                  border: 'none',
                  outline: 'none',
                  cursor: 'pointer',
                  backgroundColor: isOn ? 'var(--bg-pure)' : 'var(--border-light)',
                  color: isOn ? 'var(--text-main)' : 'var(--text-muted)',
                  fontWeight: isOn ? 700 : 600,
                  fontSize: '0.85rem',
                  boxShadow: isOn ? '0 2px 8px rgba(0,0,0,0.1)' : 'none',
                  transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
                }}
              >
                {topic.label}
              </button>
            );
          })}
        </div>
        <p style={{ fontSize: '0.85rem', color: 'var(--text-muted)', lineHeight: 1.5 }}>
          Choose what your reading feed draws from. Changes apply to newly fetched articles — stories already prepared for you will still appear first.
        </p>
      </div>

      {/* 3. Vocab Use */}
      <div style={{ backgroundColor: 'var(--bg-card)', padding: '1.5rem', borderRadius: '16px', marginBottom: '1.5rem' }}>
        <label style={{ display: 'block', fontSize: '0.85rem', fontWeight: 600, color: 'var(--text-muted)', letterSpacing: '0.1em', marginBottom: '1.5rem', textTransform: 'uppercase' }}>
          Vocab Use
        </label>
        
        <div style={{ display: 'flex', backgroundColor: 'var(--border-light)', borderRadius: '100px', padding: '4px', marginBottom: '1.2rem', height: '45px', position: 'relative' }}>
          <div style={{
            position: 'absolute',
            top: '4px',
            bottom: '4px',
            left: `calc(4px + ${(modes.findIndex(m => m.toLowerCase() === useAppStore.getState().vocabMode) === -1 ? 1 : modes.findIndex(m => m.toLowerCase() === useAppStore.getState().vocabMode))} * (100% - 8px) / 3)`,
            width: `calc((100% - 8px) / 3)`,
            backgroundColor: 'var(--bg-pure)',
            borderRadius: '100px',
            boxShadow: '0 2px 8px rgba(0,0,0,0.1)',
            transition: 'all 0.4s cubic-bezier(0.4, 0, 0.2, 1)',
            zIndex: 0
          }} />

          {modes.map((mode) => {
            const isSelected = useAppStore.getState().vocabMode === mode.toLowerCase();
            return (
              <button
                key={`v-${mode}`}
                onClick={() => useAppStore.getState().setVocabMode(mode.toLowerCase() as any)}
                style={{
                  flex: 1,
                  borderRadius: '100px',
                  backgroundColor: 'transparent',
                  color: isSelected ? 'var(--text-main)' : 'var(--text-muted)',
                  fontWeight: isSelected ? 700 : 600,
                  border: 'none',
                  outline: 'none',
                  cursor: 'pointer',
                  transition: 'color 0.4s cubic-bezier(0.4, 0, 0.2, 1)',
                  fontSize: '0.85rem',
                  display: 'flex',
                  justifyContent: 'center',
                  alignItems: 'center',
                  position: 'relative',
                  zIndex: 1
                }}
              >
                {mode}
              </button>
            );
          })}
        </div>
        
        <p style={{ fontSize: '0.85rem', color: 'var(--text-muted)', lineHeight: 1.5 }}>
          {useAppStore.getState().vocabMode === 'natural' && "Ignore priority lists. Use the most natural vocabulary for the context."}
          {useAppStore.getState().vocabMode === 'balanced' && "Prioritize natural vocabulary, but use recent study words if they are close synonyms."}
          {useAppStore.getState().vocabMode === 'study' && "Actively morph sentences to forcibly inject currently un-mastered and struggled words."}
        </p>
      </div>

      {/* 4. Kanji Use */}
      <div style={{ backgroundColor: 'var(--bg-card)', padding: '1.5rem', borderRadius: '16px', marginBottom: '1.5rem' }}>
        <label style={{ display: 'block', fontSize: '0.85rem', fontWeight: 600, color: 'var(--text-muted)', letterSpacing: '0.1em', marginBottom: '1.5rem', textTransform: 'uppercase' }}>
          Kanji Use
        </label>
        
        <div style={{ display: 'flex', backgroundColor: 'var(--border-light)', borderRadius: '100px', padding: '4px', marginBottom: '1.2rem', height: '45px', position: 'relative' }}>
          
          <div style={{
            position: 'absolute',
            top: '4px',
            bottom: '4px',
            left: `calc(4px + ${activeModeIndex} * (100% - 8px) / 3)`,
            width: `calc((100% - 8px) / 3)`,
            backgroundColor: 'var(--bg-pure)',
            borderRadius: '100px',
            boxShadow: '0 2px 8px rgba(0,0,0,0.1)',
            transition: 'all 0.4s cubic-bezier(0.4, 0, 0.2, 1)',
            zIndex: 0
          }} />

          {modes.map((mode) => {
            const isSelected = studyMode === mode.toLowerCase();
            return (
              <button
                key={`k-${mode}`}
                onClick={() => setStudyMode(mode.toLowerCase() as any)}
                style={{
                  flex: 1,
                  borderRadius: '100px',
                  backgroundColor: 'transparent',
                  color: isSelected ? 'var(--text-main)' : 'var(--text-muted)',
                  fontWeight: isSelected ? 700 : 600,
                  border: 'none',
                  outline: 'none',
                  cursor: 'pointer',
                  transition: 'color 0.4s cubic-bezier(0.4, 0, 0.2, 1)',
                  fontSize: '0.85rem',
                  display: 'flex',
                  justifyContent: 'center',
                  alignItems: 'center',
                  position: 'relative',
                  zIndex: 1
                }}
              >
                {mode}
              </button>
            );
          })}
        </div>
        
        <p style={{ fontSize: '0.85rem', color: 'var(--text-muted)', lineHeight: 1.5 }}>
          {studyMode === 'natural' && "Prioritize totally authentic and colloquial phrasing over forcing specific Kanji targets."}
          {studyMode === 'balanced' && "Prioritize authentic reading but actively substitute common synonyms that leverage your targeted Kanji pool."}
          {studyMode === 'study' && "Significantly bias the LLM to warp the article's phrasing specifically around enforcing Spaced Repetition targets, even if it feels slightly unnatural."}
        </p>
      </div>

      {/* Article Length */}
      <div style={{ backgroundColor: 'var(--bg-card)', padding: '1.5rem', borderRadius: '16px', marginBottom: '1.5rem' }}>
        <label style={{ display: 'block', fontSize: '0.85rem', fontWeight: 600, color: 'var(--text-muted)', letterSpacing: '0.1em', marginBottom: '0.5rem', textTransform: 'uppercase' }}>
          Article Length
        </label>
        <p style={{ fontSize: '0.85rem', color: 'var(--text-muted)', lineHeight: 1.5, marginBottom: '1.4rem' }}>
          Target paragraphs by how much real source text each article was built from. Full-text sources support longer reads; thin snippets stay short to avoid padding. Your JLPT level still sets the difficulty.
        </p>

        {lengthRows.map(({ kind, label, hint }) => (
          <div key={kind} style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: kind === 'snippet' ? 0 : '1.1rem' }}>
            <div style={{ marginRight: '1rem' }}>
              <div style={{ fontSize: '0.95rem', fontWeight: 600, color: 'var(--text-main)' }}>{label}</div>
              <div style={{ fontSize: '0.78rem', color: 'var(--text-muted)', lineHeight: 1.4 }}>{hint}</div>
            </div>
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', flexShrink: 0 }}>
              <button
                onClick={() => setTargetParagraphs(kind, targetParagraphs[kind] - 1)}
                disabled={targetParagraphs[kind] <= 1}
                aria-label={`Decrease ${label} length`}
                style={stepperBtnStyle(targetParagraphs[kind] <= 1)}
              >−</button>
              <span style={{ minWidth: '1.5rem', textAlign: 'center', fontSize: '1.05rem', fontWeight: 700, color: 'var(--text-main)', fontVariantNumeric: 'tabular-nums' }}>
                {targetParagraphs[kind]}
              </span>
              <button
                onClick={() => setTargetParagraphs(kind, targetParagraphs[kind] + 1)}
                disabled={targetParagraphs[kind] >= 10}
                aria-label={`Increase ${label} length`}
                style={stepperBtnStyle(targetParagraphs[kind] >= 10)}
              >+</button>
            </div>
          </div>
        ))}
      </div>

      {/* New Words Per Day (#68 — intake pacing) */}
      <div style={{ backgroundColor: 'var(--bg-card)', padding: '1.5rem', borderRadius: '16px', marginBottom: '1.5rem' }}>
        <label style={{ display: 'block', fontSize: '0.85rem', fontWeight: 600, color: 'var(--text-muted)', letterSpacing: '0.1em', marginBottom: '0.5rem', textTransform: 'uppercase' }}>
          New Words Per Day
        </label>
        <p style={{ fontSize: '0.85rem', color: 'var(--text-muted)', lineHeight: 1.5, marginBottom: '1.4rem' }}>
          How many new words graduate into active study each day, easiest and most common first — so the foundation gets built before harder words. Words you meet while reading wait in a queue until their turn. Set to 0 to pause new words.
        </p>
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
          <div style={{ fontSize: '0.95rem', fontWeight: 600, color: 'var(--text-main)' }}>New words / day</div>
          <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', flexShrink: 0 }}>
            <button
              onClick={() => setNewWordsPerDay(newWordsPerDay - 1)}
              disabled={newWordsPerDay <= 0}
              aria-label="Decrease new words per day"
              style={stepperBtnStyle(newWordsPerDay <= 0)}
            >−</button>
            <span style={{ minWidth: '1.5rem', textAlign: 'center', fontSize: '1.05rem', fontWeight: 700, color: 'var(--text-main)', fontVariantNumeric: 'tabular-nums' }}>
              {newWordsPerDay}
            </span>
            <button
              onClick={() => setNewWordsPerDay(newWordsPerDay + 1)}
              disabled={newWordsPerDay >= 50}
              aria-label="Increase new words per day"
              style={stepperBtnStyle(newWordsPerDay >= 50)}
            >+</button>
          </div>
        </div>
      </div>

      <style>{`
        details[open] .advanced-chevron {
          transform: rotate(-180deg);
        }
        details summary::-webkit-details-marker {
          display: none;
        }
      `}</style>

      {/* 5. Advanced Settings */}
      <details 
        style={{ 
          backgroundColor: 'var(--bg-card)', 
          padding: '1.5rem', 
          borderRadius: '16px', 
          marginBottom: '3rem',
          border: '1px solid var(--border-light)'
        }}
      >
        <summary style={{ fontSize: '0.85rem', listStyle: 'none', fontWeight: 600, color: 'var(--text-muted)', letterSpacing: '0.1em', textTransform: 'uppercase', outline: 'none', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
          Advanced Settings
          <ChevronDown size={18} className="advanced-chevron" style={{ transition: 'transform 0.3s ease' }} />
        </summary>
        
        <div style={{ marginTop: '1.5rem', borderTop: '1px solid var(--border-light)', paddingTop: '1.5rem' }}>
          
          {/* RTK Progression Level (Moved) */}
          <div style={{ marginBottom: '2rem' }}>
             <label style={{ display: 'block', fontSize: '0.85rem', fontWeight: 600, color: 'var(--text-main)', marginBottom: '0.75rem' }}>
              RTK Progression Level
            </label>
            <div style={{ display: 'flex', alignItems: 'center', gap: '1rem', marginBottom: '0.5rem' }}>
              <input 
                type="number" 
                value={rtkLevel || 1} 
                onChange={handleRtkChange}
                min={1}
                max={rtkKanjiList.length}
                style={{
                  padding: '0.75rem',
                  borderRadius: '8px',
                  border: '1px solid var(--border-light)',
                  backgroundColor: 'var(--bg-pure)',
                  color: 'var(--text-main)',
                  fontSize: '1.1rem',
                  width: '80px',
                  textAlign: 'center',
                  fontWeight: 600
                }}
              />
              <span style={{ color: 'var(--text-muted)', fontSize: '0.85rem', lineHeight: 1.4 }}>
                / {rtkKanjiList.length} Kanji<br/>Automatically scales up daily
              </span>
            </div>
          </div>

          <div style={{ width: '40px', height: '2px', backgroundColor: 'var(--border-light)', margin: '2rem 0' }} />

          {/* Reader Font Size */}
          <div style={{ marginBottom: '2rem' }}>
            <label style={{ display: 'block', fontSize: '0.85rem', fontWeight: 600, color: 'var(--text-main)', marginBottom: '0.75rem' }}>
              Base Reading Font Size ({readerFontSize}px)
            </label>
            <input 
              type="range" 
              min={14} 
              max={32} 
              value={readerFontSize} 
              onChange={(e) => setReaderFontSize(parseInt(e.target.value, 10))}
              style={{ width: '100%', accentColor: 'var(--text-main)' }}
            />
          </div>

          {/* Reader Bold level */}
          <div style={{ marginBottom: '1.5rem' }}>
            <label style={{ display: 'block', fontSize: '0.85rem', fontWeight: 600, color: 'var(--text-main)', marginBottom: '0.75rem' }}>
              Font Weight ({readerFontWeight})
            </label>
            <input 
              type="range" 
              min={300} 
              max={700} 
              step={100}
              value={readerFontWeight} 
              onChange={(e) => setReaderFontWeight(parseInt(e.target.value, 10))}
              style={{ width: '100%', accentColor: 'var(--text-main)' }}
            />
          </div>
          {/* Rebalance Flashcard Deck — one-time study-pacing correction (the #67
              seed-on-sight flood). Self-hides once run: the queue + pre-due window keep
              the deck healthy afterward, so it's a one-shot, not a recurring knob. */}
          {lastStudyPacingResetTs == null && (
            <>
              <div style={{ width: '40px', height: '2px', backgroundColor: 'var(--border-light)', margin: '2rem 0' }} />
              <div style={{ marginBottom: '1.5rem' }}>
                <label style={{ display: 'block', fontSize: '0.85rem', fontWeight: 600, color: 'var(--text-main)', marginBottom: '0.75rem' }}>
                  Rebalance Flashcard Deck
                </label>
                <p style={{ fontSize: '0.85rem', color: 'var(--text-muted)', lineHeight: 1.5, marginBottom: '1.2rem' }}>
                  A one-time cleanup so flashcards augment reading instead of flooding you. Words you already find easy stay scheduled but pushed far out (reading keeps them fresh); harder words move back into the queue to drip in a few per day. Nothing is deleted. You only need to run this once.
                </p>
                <button
                  onClick={async () => {
                    if (!window.confirm('Rebalance your flashcard deck? Easy words get pushed far out; harder words return to the daily queue. Nothing is deleted. This is a one-time cleanup.')) return;
                    const { useAppStore } = await import('../services/store');
                    const r = await useAppStore.getState().resetStudyPacing();
                    window.alert(`Study pacing reset.\n\n${r.keptActive} easy words kept on a far-out schedule.\n${r.requeued} words moved back to the queue (a few graduate into flashcards each day).`);
                  }}
                  style={{
                    width: '100%', padding: '0.9rem', borderRadius: '12px', backgroundColor: 'transparent',
                    color: 'var(--text-main)', border: '2px solid var(--border-light)', fontWeight: 700,
                    fontSize: '0.9rem', cursor: 'pointer', letterSpacing: '0.03em',
                  }}
                >
                  Rebalance Flashcard Deck
                </button>
              </div>
            </>
          )}

          {/* Re-align Furigana — one-time cleanup of the stored furiganaMap
              back-catalog: maps saved before the per-kanji reading tables were
              wired up (see main.tsx) carry one grouped reading per kanji run
              (意味 → いみ over the pair) instead of per-kanji splits (い/み).
              Local-only re-derive, nothing scheduled or deleted. Self-hides. */}
          {lastFuriganaRealignTs == null && (
            <>
              <div style={{ width: '40px', height: '2px', backgroundColor: 'var(--border-light)', margin: '2rem 0' }} />
              <div style={{ marginBottom: '1.5rem' }}>
                <label style={{ display: 'block', fontSize: '0.85rem', fontWeight: 600, color: 'var(--text-main)', marginBottom: '0.75rem' }}>
                  Re-align Furigana
                </label>
                <p style={{ fontSize: '0.85rem', color: 'var(--text-muted)', lineHeight: 1.5, marginBottom: '1.2rem' }}>
                  A one-time cleanup of saved furigana: readings now split per kanji (意味 → い・み), but words saved earlier still show one grouped reading. Recomputes them on this device — nothing else changes. You only need to run this once.
                </p>
                <button
                  onClick={async () => {
                    const { useAppStore } = await import('../services/store');
                    const r = await useAppStore.getState().realignFurigana();
                    window.alert(`Furigana re-aligned.\n\n${r.updated} of ${r.scanned} words updated.`);
                  }}
                  style={{
                    width: '100%', padding: '0.9rem', borderRadius: '12px', backgroundColor: 'transparent',
                    color: 'var(--text-main)', border: '2px solid var(--border-light)', fontWeight: 700,
                    fontSize: '0.9rem', cursor: 'pointer', letterSpacing: '0.03em',
                  }}
                >
                  Re-align Furigana
                </button>
              </div>
            </>
          )}

          {/* 5. Danger Zone */}
          <div style={{ padding: '1.5rem', borderRadius: '16px', border: '1px solid #ff444433', backgroundColor: '#ff444408', marginTop: '4rem', marginBottom: '1.5rem' }}>
            <h3 style={{ fontSize: '0.85rem', fontWeight: 900, color: '#ff4444', letterSpacing: '0.1em', textTransform: 'uppercase', marginBottom: '1rem' }}>Danger Zone</h3>
            <p style={{ fontSize: '0.85rem', color: 'var(--text-muted)', marginBottom: '1.5rem', lineHeight: 1.5 }}>
              Wipes your entire study history, word mastery levels, and SRS data from both your phone and the server. This cannot be undone.
            </p>
            <button
              onClick={() => {
                if (window.confirm("Nuclear Reset: Are you absolutely sure? Your entire study history will be permanently deleted.")) {
                  import('../services/store').then(m => m.useAppStore.getState().resetProgress());
                }
              }}
              style={{
                width: '100%',
                padding: '1rem',
                borderRadius: '12px',
                backgroundColor: 'transparent',
                color: '#ff4444',
                border: '2px solid #ff4444',
                fontWeight: 800,
                fontSize: '0.9rem',
                cursor: 'pointer',
                textTransform: 'uppercase',
                letterSpacing: '0.05em'
              }}
            >
              Reset All Progress
            </button>
          </div>

          {/* Acknowledgements — required attribution for the bundled dictionary. */}
          <p style={{ fontSize: '0.7rem', color: 'var(--text-muted)', lineHeight: 1.6, marginTop: '2rem', opacity: 0.7 }}>
            Japanese analysis by kuromoji.js (Apache-2.0). Dictionary data from
            mecab-ipadic, © Nara Institute of Science and Technology (NAIST). See
            THIRD_PARTY_LICENSES for full notices.
          </p>
        </div>
      </details>

    </div>
  );
}
